version: "3.9"
services:
  web:
    build:
      context: "./app"
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    ports:
      - "8220:8000"
    environment:
      FLASK_ENV: development
  # db:
  #   image: postgres:14.2-alpine
  #   restart: always
  #   environment:
  #       POSTGRES_PASSWORD: docker_lab
